/**
 * This renders a Login Form that will allow the user to login
 *
 * @author Raghavan Renganathan <renganathan.raghavan@gmail.com>
 * @version 1.0
 * @since 7/4/18
 */

import React from 'react';
import PropTypes from 'prop-types';

import logo from './../../assets/images/product-logo.svg';
import IntroContent from "../IntroContent/IntroContent";

import './LoginForm.css';
import InputTextField from "../InputTextField/InputTextField";
import CustomButton from "../CustomButton/CustomButton";

class LoginForm extends React.PureComponent {
    /**
     * Constant strings that will be used to render in this component
     */
    static CONTENT = 'Sign in';
    static SUB_CONTENT = 'to continue to the dashboard';

    static USERNAME_LABEL = 'Email or username';
    static USERNAME_ERROR = 'Enter an email or phone number';
    static PASSWORD_LABEL = 'Password';
    static PASSWORD_ERROR = 'Enter your password';

    constructor(props) {
        super(props);
        this.state = {
            username: '',
            password: '',
            usernameInvalid: false,
            passwordInvalid: false
        };
        this.handleUsernameChange = this.handleUsernameChange.bind(this);
        this.handlePasswordChange = this.handlePasswordChange.bind(this);

        this.usernameElement = React.createRef();
        this.passwordElement = React.createRef();
    }

    componentDidMount() {
        this.usernameElement.current.focus();
    }

    /**
     * This handles the state change of the username text field
     *
     * @param event {object} A React-event object generated by an event in Input Text Field
     */
    handleUsernameChange(event) {
        this.setState({
            username: event.target.value || ''
        });
    }

    /**
     * This handles the state change of the password text field
     *
     * @param event {object} A React-event object generated by an event in Input Text Field
     */
    handlePasswordChange(event) {
        this.setState({
            password: event.target.value || ''
        });
    }

    render() {
        return (
            <div className="login-form-container">
                <div className="login-form">
                    <div className="progress-bar" role="progressbar" />
                    <div className="content">
                        <IntroContent src={logo} content={LoginForm.CONTENT} subContent={LoginForm.SUB_CONTENT}/>
                        <div className="form-elements">
                            <InputTextField
                                name="username"
                                onChange={this.handleUsernameChange}
                                value={this.state.username}
                                label={LoginForm.USERNAME_LABEL}
                                errorText={LoginForm.USERNAME_ERROR}
                                invalid={this.state.usernameInvalid}
                                ref={this.usernameElement}
                            />
                            <InputTextField
                                name="password"
                                type="password"
                                onChange={this.handlePasswordChange}
                                value={this.state.password}
                                label={LoginForm.PASSWORD_LABEL}
                                errorText={LoginForm.PASSWORD_ERROR}
                                invalid={this.state.passwordInvalid}
                                ref={this.passwordElement}
                            />
                            <div className="troubleshoot-container">
                                <CustomButton
                                    theme="link"
                                    text="Trouble signing in?"
                                    noMargin
                                />
                            </div>
                            <div className="next-step-container">
                                <div className="create-account-container">
                                    <CustomButton
                                        theme="link"
                                        text="New user? Register now."
                                    />
                                </div>
                                <div className="sign-in-container">
                                    <CustomButton
                                        text="Sign in"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

LoginForm.propTypes = {
    onFormSubmit: PropTypes.func.isRequired
};

export default LoginForm;
