/**
 * This renders a Login Form that will allow the user to login
 *
 * @author Raghavan Renganathan <renganathan.raghavan@gmail.com>
 * @version 1.0
 * @since 7/4/18
 */

import React from 'react';
import PropTypes from 'prop-types';
import shortid from 'short-id';
import {LOGIN_PAGE} from '../../utils/ConstantTexts';
import InputTextField from "../InputTextField/InputTextField";

class LoginForm extends React.PureComponent {
    constructor(props) {
        super(props);
        this.values = {
            username: '',
            password: ''
        };
        this.handleUsernameChange = this.handleUsernameChange.bind(this);
        this.handlePasswordChange = this.handlePasswordChange.bind(this);
    }

    /**
     * This handles the state change of the username text field
     *
     * @param event {object} A React-event object generated by an event in Input Text Field
     */
    handleUsernameChange(event) {
        this.values.username = event.target.value || '';
    }

    /**
     * This handles the state change of the password text field
     *
     * @param event {object} A React-event object generated by an event in Input Text Field
     */
    handlePasswordChange(event) {
        this.values.password = event.target.value || '';
    }

    render() {
        return (
            <div className="login-form-container">
                <div className="login-text">
                    <span>{LOGIN_PAGE.TITLE}</span>
                </div>
                <InputTextField
                    id={shortid.generate()}
                    placeholder={LOGIN_PAGE.PLACEHOLDERS.USERNAME}
                    label={LOGIN_PAGE.LABELS.USERNAME}
                    onBlur={this.handleUsernameChange}
                />
            </div>
        );
    }
}

LoginForm.propTypes = {
    onFormSubmit: PropTypes.func.isRequired
};

export default LoginForm;
